env:
  node: true
  jest: true
  browser: true
  commonjs: true
  es6: true
parser: babel-eslint

extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-console: 0
  import/extensions: 0
  import/prefer-default-export: 0
